spring:
  application:
    name: funda-api

  profiles:
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

  h2:
    console:
      enabled: true           # H2 웹 콘솔 활성화
      path: /h2-console       # 웹 콘솔 URL

  jackson:
    time_zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

    #Consumer 설정
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"

    #Producer 설정
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        min.in.flight.requests.per.connection: 5

    #Listener 설정
    listener:
      ack-mode: manual

    health-check:
      enabled: true

jwt:
  secret-key: bXktc3VwZXItc2VjcmV0LWtleS1tdXN0LWJlLWxvbmc=
  access-token-validity: 3600
  refresh-token-validity: 604800

# Notification Sender Server Configuration
notification:
  sender:
    base-url: http://localhost:8090
    timeout: 30000 # 30초

server:
  servlet:
    context-path: /
  port: 8080

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json